env:
  GitRepo: https://$token@github.com/RobinMarchart/Life-Provider.git
  groupid: life
language: java
dist: xenial
jdk: openjdk11
before_install:
  - ./list_env_vars.sh
before_cache:
  - rm -f  $TRAVIS_BUILD_DIR/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $TRAVIS_BUILD_DIR/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $TRAVIS_BUILD_DIR/.gradle/caches/
    - $TRAVIS_BUILD_DIR/.gradle/wrapper/
deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy-site.sh
    on:
      all_branches: true
  - provider: releases
    api_key: "$token"
    file:
    - "$TRAVIS_BUILD_DIR/site/repo/$groupid/imp/$TRAVIS_BRANCH/imp-${TRAVIS_BRANCH}.jar"
    - "$TRAVIS_BUILD_DIR/site/repo/$groupid/imp/$TRAVIS_BRANCH/imp-${TRAVIS_BRANCH}-sources.jar"
    - "$TRAVIS_BUILD_DIR/site/repo/$groupid/imp/$TRAVIS_BRANCH/imp-${TRAVIS_BRANCH}-javadoc.jar"
    - "$TRAVIS_BUILD_DIR/site/repo/$groupid/api/$TRAVIS_BRANCH/api-${TRAVIS_BRANCH}.jar"
    - "$TRAVIS_BUILD_DIR/site/repo/$groupid/api/$TRAVIS_BRANCH/api-${TRAVIS_BRANCH}-sources.jar"
    - "$TRAVIS_BUILD_DIR/site/repo/$groupid/api/$TRAVIS_BRANCH/api-${TRAVIS_BRANCH}-javadoc.jar"
    skip_cleanup: true
    on:
      tags: true
