env:
  GitRepo: git@github.com:RobinMarchart/Life-Provider.git
language: java
dist: xenial
jdk: openjdk11
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy:
  provider: releases
  api_key: "$DeployKey"
  file:
  - "$HOME/api/build/libs/api.jar"
  - "$HOME/imp/build/libs/imp.jar"
  skip_cleanup: true
  on:
    tags: true
deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy-site.sh
  on:
    tags: true
